overwrite: true
schema: ${API_ENDPOINT}
documents: src/graphql/**/*.{graphql,gql}
generates:
  src/graphql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher: graphql-request
      exposeFetcher: true
      exposeQueryKeys: true
